name: ecommerce_restaurant_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  auto_route: ^7.8.4
  cloud_firestore: ^4.14.0
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  logging: ^1.2.0
  riverpod_annotation: ^2.3.3
  slang: ^3.28.0
  slang_flutter: ^3.28.0

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.7
  custom_lint: ^0.5.8
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  slang_build_runner: ^3.28.0

flutter:
  uses-material-design: true
