// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvupQnWtgwxLVmUTk5_zkyPLFFxXyB9SU',
    appId: '1:882600340312:web:038aa7cd9f5014cb71132d',
    messagingSenderId: '882600340312',
    projectId: 'appinio-restaurant-app',
    authDomain: 'appinio-restaurant-app.firebaseapp.com',
    storageBucket: 'appinio-restaurant-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0DtS6Wb3IqQXl9xIkGL_HI6AkhWmv3xE',
    appId: '1:882600340312:android:52c0b4ea7a77ec7071132d',
    messagingSenderId: '882600340312',
    projectId: 'appinio-restaurant-app',
    storageBucket: 'appinio-restaurant-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT4Sgy5Bxhigf3Fyo3amCUO9H3thQ3l-Q',
    appId: '1:882600340312:ios:df4dbc276d2da21d71132d',
    messagingSenderId: '882600340312',
    projectId: 'appinio-restaurant-app',
    storageBucket: 'appinio-restaurant-app.appspot.com',
    iosBundleId: 'com.dtengeri.ecommerceRestaurantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT4Sgy5Bxhigf3Fyo3amCUO9H3thQ3l-Q',
    appId: '1:882600340312:ios:d9f5d14fa91ac0ef71132d',
    messagingSenderId: '882600340312',
    projectId: 'appinio-restaurant-app',
    storageBucket: 'appinio-restaurant-app.appspot.com',
    iosBundleId: 'com.dtengeri.ecommerceRestaurantApp.RunnerTests',
  );
}
